### ISSUE TITLE
incompatible to IntelliJ 2018

### ISSUE THREAD

**Issue by jowilkes** [antlr/jetbrains-plugin-st4#12]
Installation of ST4 plugin fails on IntelliJ 2018 versions.
Error messages suggest it needs a different packaging (?).
Reported to IntelliJ, got delegated here. They consider disabling the plugin (if not fixed).

**Comment by parrt** [comment]
dang. I guess I will have to take a look at 2018 some time for this and ANTLR. unfortunately my head is elsewhere at the moment.

**Comment by lokkersp** [comment]
@bjansen, I think the issue can be closed because of #14

**Comment by bjansen** [comment]
ATM only @parrt can publish new versions.

**Comment by parrt** [comment]
Fixed by #14

**Comment by parrt** [comment]
@bjansen I'm getting build issues.

```
beast:master:~/antlr/code/jetbrains-plugin-st4 $ ./gradlew buildPlugin
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
```

**Comment by syakovlevdalet** [comment]
let me check with clean env.

**Comment by syakovlevdalet** [comment]
> 
> 
> @bjansen I'm getting build issues.
> 
> ```
> beast:master:~/antlr/code/jetbrains-plugin-st4 $ ./gradlew buildPlugin
> Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
> ```

fixed in #15 please review changes and accept.

**Comment by parrt** [comment]
Cool. got it. Building plugin now. worked. ok, so i should upload `build/distributions/jetbrains-plugin-st4-0.6.zip` add tag, bump version in .properties file and make release on github?

**Comment by bjansen** [comment]
I checked quickly that the plugin still works as expected when it's built by Gradle, but it's worth a second look before publishing, wdyt?

**Comment by parrt** [comment]
Sure. let me try.

**Comment by parrt** [comment]
Actually the change notes in xml file are not updated. i gotta fix that.

**Comment by bjansen** [comment]
BTW, I asked people at JetBrains [why the plugin was only compatible with IntelliJ up to 2017.x](https://gitter.im/IntelliJ-Plugin-Developers/Lobby?at=5c3f97b239596c372bf180cb), even if there was no upper bound in `plugin.xml`, and there was no clear answer:

> I'm going to go out on a limb here and say that it's probably because the repo scans for APIs used (to determine product compatibility) and has decided that the plugin uses APIs that are no longer available.

and 

> in this case, "until-build" was modified manually on plugin repository. trying to find out "why", though...

So it's still not clear to me why it "broke", and what exactly fixed it other than uploading the jar again. I'm not sure the Gradle build "fixed" anything (it certainly improves the build process a lot though).

**Comment by parrt** [comment]
ok, thanks. fixed, rerelease 0.6, pushing to plugin repo

**Comment by parrt** [comment]
Wow. cloudfront exception trying to push.

**Comment by parrt** [comment]
Ok, done. 0.6 is up.

**Comment by parrt** [comment]
uh, i can't find when i browse repos. i changed this:

```
<idea-version since-build="143.0"/>
```

Like we have for antlr plugin. was this wrong?

**Comment by parrt** [comment]
Updated to 2018.3.3 and it works.

**Comment by bjansen** [comment]
`133` was IntelliJ 13, and `143` is 15 (see https://www.jetbrains.org/intellij/sdk/docs/basics/getting_started/build_number_ranges.html).

`since-build` was bumped in the antlr plugin because of API incompatibilities IIRC, it was probably not mandatory for the ST plugin.
