### ISSUE TITLE
Antlr-based PSI?

### ISSUE THREAD

**Issue by peteruhnak** [antlr/jetbrains-plugin-st4#13]
Hi, I'd like to ask whether it is possible to somehow generate PSI classes from the antlr grammar, as PSI is needed to provide some advanced features such as code completion, etc. Or would that require rewriting the grammar into BNF/Flex?

**Comment by parrt** [comment]
I think for this plugin I did everything manually whereas the antlr plugin has a PSI bridge I think. maybe look at that one?

**Comment by bjansen** [comment]
@peteruhnak version 0.7 of the plugin will now include a PSI tree, although it's not yet used for things like syntax highlighting.
