### ISSUE TITLE
.stg files don't have an icon

### ISSUE THREAD

**Issue by Clashsoft** [antlr/jetbrains-plugin-st4#16]
See attached screenshot. The icon is just one black pixel. Using IntelliJ 2019.3, plugin 0.6.

![Screenshot 2019-12-17 at 13 28 51](https://user-images.githubusercontent.com/4145923/70995575-2b9a2f00-20d1-11ea-90b5-9fbbd568de61.png)

**Comment by parrt** [comment]
thanks, @bjansen !!
