### ISSUE TITLE
Code Folding

### ISSUE THREAD

**Issue by Clashsoft** [antlr/jetbrains-plugin-st4#17]
It would be really useful if one could fold template bodies in .stg files. See attached screenshot for an example, using IntelliJs custom folding regions (which unfortunately don't work very well when the code changes):

![Screenshot 2019-12-17 at 13 30 42](https://user-images.githubusercontent.com/4145923/70995733-8764b800-20d1-11ea-8665-09d660e1b4a4.png)

**Comment by Clashsoft** [comment]
Unfortunately doesn't work with `<% %>`, `<if>`, `[ ]` and probably others :(

**Comment by bjansen** [comment]
It should be fairly easy to implement that too.

**Comment by bjansen** [comment]
BTW dicts are already supported:

![image](https://user-images.githubusercontent.com/281528/84478909-605afd80-ac92-11ea-86fb-662ff9b08357.png)

**Comment by Clashsoft** [comment]
Oh yes, my mistake, the dicts work indeed :)

**Comment by bjansen** [comment]
Fixed in 0b5b12a4abf948cf57156cc344c8e973de45fa47
