### ISSUE TITLE
Error markers have no tooltip

### ISSUE THREAD

**Issue by Clashsoft** [antlr/jetbrains-plugin-st4#18]
Most (all?) errors are highlighted, but have no tooltip that gives further information about the problem. See attached screenshot (hovering the mouse over the red text does nothing).

![Screenshot 2019-12-17 at 13 34 05](https://user-images.githubusercontent.com/4145923/71001519-bf71f800-20dd-11ea-9ea9-0591d0e79d21.png)

**Comment by bjansen** [comment]
I have the same problem in Java and Typescript files, I suspect a bug in IntelliJ itself (maybe https://youtrack.jetbrains.com/issue/IDEA-187030). 
Does it work correctly in non-STG files on your machine?

**Comment by Clashsoft** [comment]
No popup appears, not even for a short time. There is also no error in the status bar. The tooltips work for errors in Java files, at least.

**Comment by parrt** [comment]
Dang. Yeah, I don't use st4 plugin much but I don't remember problems when viewing large templates recently.

**Comment by Clashsoft** [comment]
The problem also occurs when the .stg file has no other content:

```
value
```

**Comment by bjansen** [comment]
It's not really a bug, just a feature that wasn't entirely implemented :)
