### ISSUE TITLE
Colors unusable in Dracula scheme

### ISSUE THREAD

**Issue by MarekMalevic** [antlr/jetbrains-plugin-st4#2]
I am using dark Idea scheme Dracula and when I open the stg file, the colors are very bad because the default white palette is expected. It prevents the plugin to be usable.

The colors should take existing scheme or be configurable.
![image](https://cloud.githubusercontent.com/assets/7595015/11253214/763ff748-8e3a-11e5-916f-40fa8a5124ae.png)

**Comment by cy6erGn0m** [comment]
Yes, you need separate schema for Dracula, like this:

```xml
<additionalTextAttributes scheme="Default" file="colorSchemes/STGroupDefault.xml"/>
<additionalTextAttributes scheme="Default" file="colorSchemes/STGroupDracula.xml"/>
```

and also it would be great to create settings page, but it requires slightly more work to do

```xml
<colorSettingsPage implementation="rg.antlr.jetbrains.st4plugin.STGroupColorSettingsPage"/>
```

```kotlin
class STGroupColorSettingsPage : ColorSettingsPage {
 // ...
```

**Comment by MarekMalevic** [comment]
final EditorColorsScheme scheme = editorColorsManager.getGlobalScheme();

fixes the issue for me. I am not able to push my branch here.

**Comment by parrt** [comment]
Hi guys. I just abstracted out my antlr-intellij bridge stuff. Now I can change this plugin to use PSI not antlr parse trees: https://github.com/antlr/jetbrains.  On the other hand, it's working. perhaps a pull request? STGroupColorSettingsPage is hard w/o using PSI trees.

**Comment by bosyak** [comment]
Please :) it's still looks bad

**Comment by rbellamy** [comment]
@cy6erGn0m or @MarekMalevic - I'd love to see this corrected, an I think @parrt was hoping someone that knows what their doing (which you can read as "not me") would offer up a PR...

And of course I'm gently poking the bear here cuz it's affecting me... and I'm not conversant enough with PSI trees or IntelliJ plugin development to know where to start...

**Comment by dbelyavsky** [comment]
so no responses since December, and no updates, either (virtually)no one using the plugin with dark theme or is there a workaround that I can use?
@MarekMalevic : does your change go into `SyntaxHiglighter.java`

**Comment by rbellamy** [comment]
@dbelyavsky I use the quick color scheme changer when working with template files... And then switch back when I'm done. Not ideal, but it keeps me moving.

**Comment by parrt** [comment]
Guys, I *thought* i figured it out with last release. I had people check it. looks good for me.
<img width="662" alt="screen shot 2016-09-07 at 5 02 06 pm" src="https://cloud.githubusercontent.com/assets/178777/18332597/d58df582-751c-11e6-8846-72e3fa3f229e.png">

**Comment by parrt** [comment]
I guess I forgot to close this

**Comment by parrt** [comment]
OH!

**Comment by parrt** [comment]
ok, how's this?
<img width="548" alt="screen shot 2016-09-08 at 5 31 50 pm" src="https://cloud.githubusercontent.com/assets/178777/18371561/397390c0-75ea-11e6-827f-02f7060346b4.png">

**Comment by parrt** [comment]
try installing this plugin
[jetbrains-plugin-st4.zip](https://github.com/antlr/jetbrains-plugin-st4/files/462966/jetbrains-plugin-st4.zip)

**Comment by dbelyavsky** [comment]
yep, looks much better now -- thanks!
<img width="506" alt="screen shot 2016-09-08 at 22 04 13" src="https://cloud.githubusercontent.com/assets/19421416/18373252/956ddb44-7610-11e6-8f1c-f21930e0ee8f.png">

**Comment by rbellamy** [comment]
Looks much better - worked for me.

**Comment by parrt** [comment]
hooray! I hope to get some time to work more on plug-ins and ANTLR in October November.

**Comment by novaterata** [comment]
@parrt I'm using 2016.2.5 and stg highlighting is unusable with Darcula still. Is this because this fix will be in 0.5?

**Comment by novaterata** [comment]
@parrt That must be it, I downloaded the above zip and that fixed it; although, I find that blue unreadable. Is it 0,0,127? I always have to set that to 0,0,255 in cmd.exe for example. Based on discussions of LSCOLORS it must be a Windows thing.

**Comment by parrt** [comment]
I hope to push out the new version shortly

**Comment by parrt** [comment]
I'm working on this again for release soon. colors are a big wonky still:

<img width="280" alt="screen shot 2016-12-20 at 11 03 18 am" src="https://cloud.githubusercontent.com/assets/178777/21364029/ee386486-c6a3-11e6-8fd8-acccb3d665fb.png">

**Comment by parrt** [comment]
@novaterata @dbelyavsky @rbellamy 0.5b2 for ya. Better colors now i think.
[jetbrains-plugin-st4.zip](https://github.com/antlr/jetbrains-plugin-st4/files/664605/jetbrains-plugin-st4.zip)
