### ISSUE TITLE
Color settings page

### ISSUE THREAD

**Issue by Clashsoft** [antlr/jetbrains-plugin-st4#21]
Allow the syntax highlighting colors to be configured with a settings page.

**Comment by bjansen** [comment]
Coming soon :)

![image](https://user-images.githubusercontent.com/281528/86099679-1d818e00-bab8-11ea-80bb-98baa0a268ca.png)

**Comment by bjansen** [comment]
Fixed, will be released in 0.9

**Comment by Clashsoft** [comment]
Thank you, it looks great!
