### ISSUE TITLE
Highlight missing <endif>

### ISSUE THREAD

**Issue by Clashsoft** [antlr/jetbrains-plugin-st4#22]
Since there is no completion (#20) yet, it is easy to miss an `<endif>`. As such, it would be very useful if this fact were highlighted with an error indicator.

At runtime, this problem is reported as `premature EOF` at a seemingly random line in the file, which is very hard to figure out.

![Screenshot 2019-12-19 at 12 59 47](https://user-images.githubusercontent.com/4145923/71172001-7184fd80-225f-11ea-9b6b-1b5cb4106a0c.png)

**Comment by Clashsoft** [comment]
As of 0.7, it now looks like this:

<img width="270" alt="Screenshot 2020-06-12 at 00 22 21" src="https://user-images.githubusercontent.com/4145923/84444767-ca4bb680-ac42-11ea-863a-048b13b02ca1.png">

The error message is not perfectly clear but it's better than nothing.

**Comment by bjansen** [comment]
I'm not sure how we could tell the parser to report a better error message. I believe the message is intentionally "vague" because at this point there could be `<elseif>`, `<else>` or `<endif>`, all of which start with the `LDELIM` token. @parrt what do you think?

**Comment by parrt** [comment]
Yes, the parser only knows that it has to have a tag to go with that and, as it likely is missing `<` as a token (not a char), probalby best we can do

**Comment by Clashsoft** [comment]
Alright then, if it's too much work. I'm personally already happy with that error message.
