### ISSUE TITLE
Support `.st` files

### ISSUE THREAD

**Issue by mikebski** [antlr/jetbrains-plugin-st4#24]
Support `.st` file highlighting - I'm using Intellij and st4 to generate HTML and this would be awesome.

I'm willing to help, just not sure where to start with Intellij plugins. Any insight as to where to start would be helpful, too.

**Comment by bjansen** [comment]
Here's a good starting point: https://www.jetbrains.org/intellij/sdk/docs/tutorials/custom_language_support_tutorial.html

You can probably adapt what was already done for st4 files without too much trouble.

The harder part will be ST templates which are embedded in ST groups, but I guess that's outside the scope of what you are trying to do.

**Comment by bjansen** [comment]
Fixed in 0b5b12a4abf948cf57156cc344c8e973de45fa47

**Comment by Clashsoft** [comment]
Now that this is done, the readme should be updated:

> It understands .stg files (not .st files yet). For example,

**Comment by bjansen** [comment]
Yep, I had this change in a pending commit that I just pushed. Thanks for reminding me :)
