### ISSUE TITLE
Does not work with IntelliJ 2020.1

### ISSUE THREAD

**Issue by Clashsoft** [antlr/jetbrains-plugin-st4#25]
Using IntelliJ 2020.1 and this plugin v0.6, `stg` files show as plain text.

![Screenshot 2020-04-14 at 12 57 20](https://user-images.githubusercontent.com/4145923/79217645-7ba2bb80-7e4f-11ea-8d96-0a5f0f3247ef.png)

**Comment by FHannes** [comment]
I am also running into this issue with 2020.1. It seems that the `STGroupHighlightingPassFactory` is registered in the `TextEditorHighlightingPassRegistrarImpl`, but it gets erased again in the `TextEditorHighlightingPassRegistrarImpl.reregisterFactories()` method. I am guessing the method of registering these has changed, as seems to be indicated here: https://www.jetbrains.org/intellij/sdk/docs/reference_guide/api_notable/api_notable_list_2019.html

> **Notable Changes in IntelliJ Platform 2019.2**
> `com.intellij.codeHighlighting.TextEditorHighlightingPassFactory` registration
>     Use new dedicated extension point `com.intellij.highlightingPassFactory`.

**Comment by bjansen** [comment]
@parrt the problem seems to be fixed. I can make a release if you want, but you have to add me as a contributor on plugins.jetbrains.com first.

**Comment by parrt** [comment]
@bjansen wow. i literally cannot find a way to do this on their site. got a link for me? I'm starting at [plugin](https://plugins.jetbrains.com/plugin/8041-stringtemplate-v4-plugin)

**Comment by bjansen** [comment]
There's an edit button right next to the `General Information` section:

![image](https://user-images.githubusercontent.com/281528/83951900-42763e80-a835-11ea-97b5-86857c3f5409.png)

**Comment by parrt** [comment]
yeah, saw that and i used your id but it didn't find you so thought it was just a "name". lemme try again

**Comment by parrt** [comment]
Ha! works with name not id. high-larious. done.

**Comment by bjansen** [comment]
👍 thanks!
