### ISSUE TITLE
Double-click word selection is broken

### ISSUE THREAD

**Issue by Clashsoft** [antlr/jetbrains-plugin-st4#31]
When double-clicking within a template to select a word, only a single letter is selected instead. This happens only for verbatim text, not for keywords or insertions.

Here's a recording, with the following steps:

1. Press Alt-Shift-Left to select the verbatim word (works as intended).
2. Double-click with the intention to select the verbatim word, but it only selects one letter.
3. Double-click to select the word within the attribute insertion (works as intended).
4. Double-click to select the keyword `if` (also works as intended).

It's not in the recording, but double-click also works for template and attribute names. So the problem seems to occur only in verbatim text.

![recording](https://user-images.githubusercontent.com/4145923/93017050-11d93a00-f5c6-11ea-9c6f-e43afb3d2448.gif)

**Comment by parrt** [comment]
Thanks. i think i've seen something like this.

**Comment by bjansen** [comment]
It probably happens because these characters are lexed as individual tokens. Having a single token that represents the whole 'template' text should fix the problem (I think that's how I fixed it in pebble-intellij).

**Comment by bjansen** [comment]
Btw @parrt can you think of a better way than this to merge consecutive tokens of the same type? 

https://github.com/bjansen/pebble-intellij/blob/master/parser/src/main/antlr/com/github/bjansen/pebble/parser/PebbleLexer.g4#L26-L41

**Comment by Clashsoft** [comment]
@bjansen all rules except `CONTENT` start with `{`, so could you not use this?

```antlr
CONTENT
    : ~[{]+
    ;

**Comment by parrt** [comment]
the filter in the pebble lexer seems okay to me but doing it in the grammar role might be easier as @Clashsoft says

**Comment by bjansen** [comment]
Apparently one of the recent changes in `master` already fixed the problem (probably the language injection thing). 
@Clashsoft could you try this build and let me know if the bug persists?

[jetbrains-plugin-st4-0.9-SNAPSHOT.zip](https://github.com/antlr/jetbrains-plugin-st4/files/5217702/jetbrains-plugin-st4-0.9-SNAPSHOT.zip)

**Comment by Clashsoft** [comment]
@bjansen with language injection the selection is indeed fixed. Although I couldn't find a way to turn the language injection off and test it. Perhaps you should still aim for improving the lexer grammar, if only for performance reasons :)

**Comment by bjansen** [comment]
Language injection can't be "turned off" afaik, it will default to "plain text file".
