### ISSUE TITLE
Support selection on plain text words, by double-click, as well as only template words

### ISSUE THREAD

**Issue by rwperrott** [antlr/jetbrains-plugin-st4#38]
It's annoying that I have to manually select words outside of a template use.

**Comment by bjansen** [comment]
Agreed, although I think it's already been fixed as a side-effect of  #29. Could you try this build and let me know if it fixes your problem?

[jetbrains-plugin-st4-0.9-SNAPSHOT.zip](https://github.com/antlr/jetbrains-plugin-st4/files/5687747/jetbrains-plugin-st4-0.9-SNAPSHOT.zip)

Installation instructions are available here : https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk

**Comment by rwperrott** [comment]
Yes, it's fixed in 0.9.

**Comment by Clashsoft** [comment]
FYI, this may be a duplicate of #31

**Comment by bjansen** [comment]
@Clashsoft You're right, it is :)
