### ISSUE TITLE
Incorrect highlighting inside strings

### ISSUE THREAD

**Issue by Moritz90** [antlr/jetbrains-plugin-st4#5]
I've defined a map inside one of my templates:

```
typeMap ::= [
  "list<int>": "std::vector<int>",
  "list<long>": "std::vector<long>",
  "list<float>": "std::vector<float>",
  "list<double>": "std::vector<double>"
]
```

In the above code, `<int>`, `<long>`, ... are highlighted like attribute references.

**Comment by parrt** [comment]
Hi.  Oddly enough, that is correct behavior. `<int>` It is a StringTemplate expression referring to an attribute called `int` using the default angle bracket delimiters.

**Comment by Moritz90** [comment]
Then why doesn't StringTemplate interpret it as such? I get no "undefined attribute" warning and

```
typeMap ::= [
  "list\<int>": "std::vector\<int>",
  "list\<long>": "std::vector\<long>",
  "list\<float>": "std::vector\<float>",
  "list\<double>": "std::vector\<double>"
]
```

produces incorrect behavior (backslashes end up in output).

So this is either a bug in StringTemplate itself or in the plugin.

**Comment by parrt** [comment]
It is because of lazy evaluation. bad attrs can only be detected at ST exec time.

**Comment by Moritz90** [comment]
Ok, in that case both the highlighting and StringTemplate's behavior would make sense. It's still very confusing, though.

**Comment by parrt** [comment]
@Moritz90 I think that this is because the key is just a plain string but the value is interpreted as a template.
