### ISSUE TITLE
Project should is not ready for checkout

### ISSUE THREAD

**Issue by cy6erGn0m** [antlr/jetbrains-plugin-st4#6]
It should be way to clone and build project somehow but now it is just dead. I even can't generate parser by antlr4 tool

so I was expecting the following flow
1. clone
2. generate parsers, aka './generate.sh`
3. open project, select IDEA SDK
4. Chose run configuration and run

**Comment by parrt** [comment]
hiya. wow. somebody is using the plugin! ...and wants to build. ok. with STGLexer.g4 and STGParser.g4 and STParser.g4, right click to get config dialog. Now set package to `org.antlr.jetbrains.st4plugin.parsing`.
![screen shot 2015-12-03 at 10 14 59 am](https://cloud.githubusercontent.com/assets/178777/11569451/d339f9f4-99a6-11e5-8105-63ae5c713d8c.png)

Now just hit "generate" action via right-click in grammar window.
