### ISSUE TITLE
Include antlr4 commands used in README

### ISSUE THREAD

**Issue by rbellamy** [antlr/jetbrains-plugin-st4#8]
Wanted to give the colorization work a quick look, tried opening the project as-is and got stuck on https://github.com/antlr/grammars-v4/issues/274. This leads me to think I'm doing something wrong. Without a doubt it's been a long time since I worked with ANTLR and what little skill I had then is long-gone now...

Maybe including the correct incantations in the README.MD would make things go more smoothly?

**Comment by parrt** [comment]
Hmm...`mvn test` seems to be working for me, although it may fail on one of the tests that I merged by mistake.

**Comment by parrt** [comment]
wait, you're not talking about the grammars-v4 dir, but the ST plugin. hmm...yeah, it would be good to add the incantation; I don't think I have a pom.xml file for that.

**Comment by parrt** [comment]
@rbellamy   What I do is manually right-click, believe it or not, on the grammar and tell it to generate into the root/gen dir. ;) Then I launch. I kinda figured I'd be the only one playing around with this but I guess I should get a pom.xml together.
